### ISSUE TITLE
Just making sure there's not a systemic issue; WALKER, JR., John E.

### ISSUE THREAD

**Issue by Mbjoerkh** [Vandivier/data-science-practice#15]
Are we missing academic years for the "second entry" of this guy because he's missing a degree year for his MA degree? Or is something else going on? In source we have academic years 1958-1959 and 1959-1960.

**Comment by Mbjoerkh** [comment]
Similar issue with LAMB, Theresa R. : 
missing academic year - I can't find a reason for it in the source.

**Comment by Vandivier** [comment]
You may have seen it, but here is the logic to get the academic year:

    /**
     * assume the pattern is [year 0...year n], school, field / sAreaOfStudy, name, 'Sponsor', completion degree
     * exception: If a valid year comes just after a completion degree,
     * it is not an academic year it is a completion year
     **/
    function fParseAcademicYear(oRecord, oSponsor) {
        let arrsAcademicYears = [],
            iYearCandidateIndex = oSponsor.index - 4,
            sToCheckCompletionYear,
            sToCheckAcademicYear;

        while (iYearCandidateIndex + 1) { // iYearCandidateIndex shouldn't be negative
            sToCheckCompletionYear = oRecord.arrSplitByComma[iYearCandidateIndex - 1];
            sToCheckAcademicYear = oRecord.arrSplitByComma[iYearCandidateIndex];

            if (!arrDegrees.includes(sToCheckCompletionYear)) { // completion year exception check
                if (fCheckAcademicYear(sToCheckAcademicYear)) {
                    arrsAcademicYears.push(sToCheckAcademicYear);
                } else {
                    break; // don't keep looking or you might encounter valid years from an invalid location, such as a different sponsorship record for the same student
                }
            } else {
                oSponsor.sCompletionYear = sToCheckCompletionYear;
            }

            iYearCandidateIndex--;
        }

        oSponsor.sAcademicYear = arrsAcademicYears.join(',');
    }

This issue is valid and I'm not sure but may be related to an erroneous index. I'll check further after work. Can you confirm a couple similar entries are working as expected?
1. L'ARRIVEE, Elizabeth   A.
2. GRAHAM, Fred C.

**Comment by Mbjoerkh** [comment]
1. and 2. are both good!

**Comment by Vandivier** [comment]
string to search for walker: WALKER JR., John E.

**Comment by Vandivier** [comment]
So there is a systematic problem! an edge case but a problem. we met and fixed it.

WALKER JR., John E. has been fixed in Master. Please repeat this fix pattern for the other occurrences and we can loop back for additional issues.

The fix is to explicitly state in source "NO DOCUMENTED COMPLETION YEAR" for intermediate degrees without a documented completion year. Technically, any string will do the trick but this is our agreed convention. Full example source record below:

WALKER JR., John E. 
Graduate Fellowship(s) 
1958-1959 
University of Virginia, Economics, 
G. Warren Nutter and James M. Buchanan, Sponsors, M.A., NO DOCUMENTED COMPLETION YEAR, 
1959-1960 
University of Virginia, Economics, 
G. Warren Nutter and James M. Buchanan, Sponsors, Ph.D., 1963 
Address,
4317 Sanctuary Way, Bonita Springs, FL 
34134-8723 
WALKER, Robert Lewis

**Comment by Vandivier** [comment]
did we confirm this is fixed? I'd like to close the issue

**Comment by Mbjoerkh** [comment]
Thanks for reminding me! I just confirmed both cases to be fixed.
